### ISSUE TITLE
Do I need to make a purchase to use this bundle?

### ISSUE THREAD

**Issue by prunepal333** [BlackbitDigitalCommerce/pimcore-custom-field-settings#1]
I couldn't find source in the github repository, what is the procedure to make use of this bundle?

**Comment by BlackbitDevs** [comment]
Hi @prunepal333,

it is a paid bundle. Please have a look at https://shop.blackbit.com/pimcore-custom-field-settings/ if you are interested or write to info@blackbit.com

I will update the Readme to immediately point this out.
